<a href="https://colab.research.google.com/github/dhadkan99/Artificial-Intelligence-and-Machine-Learning--6CS012/blob/main/Workshop_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.1 Exercise on Functions


### Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).  
2. Ask the user to input the value to be converted.  
3. Perform the conversion and display the result.  
4. Handle potential errors, such as invalid input or unsupported conversion types.  

• Requirements:

1. Functions: Define at least one function to perform the conversion.  
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).  
3. User Input: Prompt the user to select the conversion type and input the value.  
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.  

• Conversion Options:

1. Length:  
– Convert meters (m) to feet (ft).  
– Convert feet (ft) to meters (m).  

2. Weight:  
– Convert kilograms (kg) to pounds (lbs).  
– Convert pounds (lbs) to kilograms (kg).  

3. Volume:  
– Convert liters (L) to gallons (gal).  
– Convert gallons (gal) to liters (L).  


In [ ]:
def convert_units(conversion_type: str, value: float) -> float:
    """
    Convert a value between supported measurement units.

    Args:
        conversion_type (str): Type of conversion
            (m_to_ft, ft_to_m, kg_to_lbs, lbs_to_kg, l_to_gal, gal_to_l)
        value (float): Numeric value to convert

    Returns:
        float: Converted value
    """
    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type")


print("Choose conversion type:")
print("1. m_to_ft")
print("2. ft_to_m")
print("3. kg_to_lbs")
print("4. lbs_to_kg")
print("5. l_to_gal")
print("6. gal_to_l")

try:
    choice = input("Enter conversion type: ").strip()
    value = float(input("Enter value: ").strip())

    result = convert_units(choice, value)
    print(f"Converted value: {result:.4f}")

except ValueError as e:
    print(f"Error: {e}")

Choose conversion type:
1. m_to_ft
2. ft_to_m
3. kg_to_lbs
4. lbs_to_kg
5. l_to_gal
6. gal_to_l
Enter conversion type: kg_to_lbs
Enter value: 80
Converted value: 176.3696


## Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.

4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.


In [ ]:
def perform_operations(operation_type: int, numbers: list) -> float:
    """
    Calculates the sum, average, maximum or minimum of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The mathematical operation of the numbers.
    """
    if operation_type == 1:
      return sum(numbers)
    elif operation_type == 2:
      return sum(numbers) / len(numbers)
    elif operation_type == 3:
      return max(numbers)
    elif operation_type == 4:
      return min(numbers)


print("Choose an operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = input("Enter operation choice (1-4): ").strip()
    if choice not in ["1", "2", "3", "4"]:
        raise ValueError("Invalid operation choice")

    numbers_input = input("Enter a list of numbers separated by spaces: ").strip()

    if not numbers_input:
        raise ValueError("Input list cannot be empty.")

    numbers = [float(num) for num in numbers_input.split()]

    print(perform_operations(int(choice), numbers))

except ValueError as e:
    print(f"Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter operation choice (1-4): 1
Enter a list of numbers separated by spaces: 5 7 9
21.0


## 4.2 Exercise on List Manipulation


In [ ]:
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Returns sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Reverses a list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Extracts first n elements."""
    return lst[:n]

def get_last_n(lst, n):
    """Extracts last n elements."""
    return lst[-n:]

def reverse_skip(lst):
    """Reverse order starting from second-to-last, skipping one."""
    return lst[-2::-2]

# --- Execution Tests ---
my_list = [1, 2, 3, 4, 5, 6]
print("Every Other:", extract_every_other(my_list))   # Output: [1, 3, 5]
print("Sublist (2-4):", get_sublist(my_list, 2, 4)) # Output: [3, 4, 5]
print("Reverse Skip:", reverse_skip(my_list))        # Output: [5, 3, 1]

Every Other: [1, 3, 5]
Sublist (2-4): [3, 4, 5]
Reverse Skip: [5, 3, 1]


4.3 Exercise on Nested List

In [ ]:
def flatten(lst):
    """Flattens a 2D list into 1D."""
    return [item for sublist in lst for item in sublist]

def access_nested_element(lst, indices):
    """Accesses element using a list of indices."""
    for i in indices:
        lst = lst[i]
    return lst

def sum_nested(lst):
    """Recursive sum of all numbers in any nested depth."""
    total = 0
    for i in lst:
        total += sum_nested(i) if isinstance(i, list) else i
    return total

def remove_element(lst, elem):
    """Removes all occurrences of elem from nested list."""
    return [remove_element(i, elem) if isinstance(i, list) else i for i in lst if i != elem]

def find_max(lst):
    """Finds maximum value in a deeply nested list."""
    def get_all(l):
        for i in l:
            yield from get_all(i) if isinstance(i, list) else [i]
    return max(list(get_all(lst)))

def deep_flatten(lst):
    """Flattens list of any depth."""
    res = []
    for i in lst:
        res.extend(deep_flatten(i)) if isinstance(i, list) else res.append(i)
    return res

def average_nested(lst):
    """Calculates average of all elements in nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

nested = [[1, 2], [3, [4, 5]], 6]
print("Flattened:", deep_flatten(nested))
print("Total Sum:", sum_nested(nested))
print("Max Value:", find_max(nested))

Flattened: [1, 2, 3, 4, 5, 6]
Total Sum: 21
Max Value: 6


# 10.1 Basic Vector and Matrix Operation with Numpy

In [ ]:
import numpy as np

# Problem 1: Array Creation
arr_empty = np.empty((2, 2))
arr_ones = np.ones((4, 2))
arr_full = np.full((3, 3), 5)
arr_zeros_like = np.zeros_like(arr_full)
arr_ones_like = np.ones_like(arr_full)
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)

# Problem 2: Manipulation
range_arr = np.arange(10, 50)
matrix_3x3 = np.arange(9).reshape(3, 3)
identity_3x3 = np.eye(3)
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()
rand_10x10 = np.random.random((10, 10))
min_val, max_val = rand_10x10.min(), rand_10x10.max()
zero_10 = np.zeros(10)
zero_10[4] = 1 # Replace 5th element
rev_arr = np.array([1, 2, 0, 0, 4, 0])[::-1]
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# Problem 3: Operations
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Addition:\n", x + y)
print("Square:\n", np.square(x))
print("Dot x and y:\n", np.dot(x, y))
print("Concatenate x and y (rows):\n", np.vstack((x, y)))

# Observation Task 7
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"\nConcatenation Error: {e}")
    print("Reason: You cannot concatenate a 2x2 matrix with a size 2 vector along rows without reshaping.")

# Problem 4: Matrix Operations
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.inv(A) = I
inv_A = np.linalg.inv(A)
print("\nA * inv(A) is Identity:\n", np.allclose(A @ inv_A, np.eye(2)))

# 2. Solve Linear System:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
coeffs = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
consts = np.array([-1, -3, 9])
solution = np.linalg.solve(coeffs, consts)
print("\nSolution (x, y, z):", solution)

Addition:
 [[ 6  8]
 [10 13]]
Square:
 [[ 1  4]
 [ 9 25]]
Dot x and y:
 [[19 22]
 [50 58]]
Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: You cannot concatenate a 2x2 matrix with a size 2 vector along rows without reshaping.

A * inv(A) is Identity:
 True

Solution (x, y, z): [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

In [ ]:
import time

size = 1000000
list1, list2 = list(range(size)), list(range(size))
arr1, arr2 = np.arange(size), np.arange(size)

# Python List Addition
start = time.time()
res_list = [list1[i] + list2[i] for i in range(size)]
print(f"Python List Addition: {time.time() - start:.5f}s")

# Numpy Array Addition
start = time.time()
res_arr = arr1 + arr2
print(f"Numpy Array Addition: {time.time() - start:.5f}s")

Python List Addition: 0.10810s
Numpy Array Addition: 0.00614s
